AWSTemplateFormatVersion: 2010-09-09
Description: >-
  tampopo
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
  GetWeatherForecast:
    Type: AWS::Serverless::Function
    Properties:
      Description: Get weather forecast and send a message via LINE
      Runtime: nodejs22.x
      Architectures:
      - x86_64
      Handler: src/handlers/get-weather-forecast.getWeatherForecastHandler
      MemorySize: 128
      Timeout: 100
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(15 15 * * ? *)
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
